spring:
  application:
    name: userTest #服务名字

eureka:
  client:
    service-url:
     defaultZone: http://node1:8761/eureka/,http://node2:8762/eureka/ #注册中心集群地址
server:
  port: 8082 #服务端口

env:
  aaaaa
